version: '3.8'
x-app: &base-app
  build:
    context: '.'
  depends_on:
    - "postgres"
    - "redis"
  env_file:
    - .env
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true

services:
  app:
    <<: *base-app
    container_name: app
    entrypoint: [ '/app-entrypoint.sh' ]
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/check_health/}"
      interval: "60s"
      timeout: "3s"
      retries: 3
    ports:
      - "8000:8000"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    logging:
      driver: none
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    build: ./redis
    container_name: redis
    logging:
      driver: none
    volumes:
      - ./redis/backup:/data
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    restart: "on-failure"

volumes:
  postgres_volume:
    name: notion_postgres_volume